# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 56853743bb00dc2c33ff3102897ab2ec525b0342b16b0a80dc6d46455fbed202d5cb7e1ff296450800b08e7e9f3a5c7dcaed8e1e192bd8f406640b375caefab9

test:
  secret_key_base: eeba5a469673990f0dd2324740bf81d23df157b5e54f7dae0e2bf94949c43ca5362ae06fb62bd89fbf1d952e590289b504798eab83a64d5652fbb60ad478990f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
